name: websocket_universal
description: |
  Convenient websocket handler for all platforms (both IO and web/HTML).
  Websocket messages routing, statuses and other features have easy-to-use
  interface.

version: 1.2.4
repository: https://github.com/dvmatyun/web_socket
issue_tracker: https://github.com/dvmatyun/web_socket/issues
homepage: https://github.com/dvmatyun/web_socket

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  json_annotation: ^4.8.1
  meta: ^1.2.0

dev_dependencies:
  json_serializable: ^6.7.1
  lints: ^3.0.0
  build_runner: ^2.4.7
  test: any
  coverage: any
